import Link from 'next/link'
import type { Metadata } from 'next'

import WriteIcon from './components/WriteIcon'

import { Inter, Sevillana } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const sevillana = Sevillana({
    subsets: ['latin'],
    display: 'swap',
    weight: '400'
})

export const metadata: Metadata = {
  title: 'Gyu-Stargram',
  description: 'Generated by create next app',
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className='w-[800px] mx-auto'>
                    <nav className='shadow-[0_1px_2px_0_rgba(0,0,0,0.1)] sticky top-0 bg-white flex justify-between items-center p-3'>
                        <h1 className={`${sevillana.className} text-3xl`}>
                            <Link href='/'>Gyu-Stargram</Link>
                        </h1>
                        <Link href='/write'>
                            <WriteIcon />
                        </Link>
                    </nav>
                    {children}
                </div>
            </body>
        </html>
    )
}
